### ISSUE TITLE
Mapa Mental realizado por Eduardo Tomas Feria Ortiz del 1AS

### ISSUE THREAD

**Issue by Eduardo21620095** [SistemasTecTlaxiaco/mapa-mental-Eduardo21620095#2]
[MAPA_MENTAL_CONJUNTOSYRELACIONES_EDUARDO_TOMAS_FERIA_ORTIZ_1AS.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-Eduardo21620095/files/7377991/MAPA_MENTAL_CONJUNTOSYRELACIONES_EDUARDO_TOMAS_FERIA_ORTIZ_1AS.pdf)

**Comment by lucero012** [comment]
de acuerdo a la rubrica. te doy un 15% te faltan algunas definiciones.

**Comment by josealfredo79** [comment]
Este trabajo se debe complementar para mejorarlo...

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado...solo tomar en cuenta el trabajo que se pide.
