### ISSUE TITLE
MAPA MENTAL SEGUNDA OPORTUNIDAD EDUARDO TOMAS 1AS

### ISSUE THREAD

**Issue by Eduardo21620095** [SistemasTecTlaxiaco/mapa-mental-Eduardo21620095#3]
[MAPA_MENTAL_CONJUNTOSYRELACIONES_EDUARDO_TOMAS_FERIA_ORTIZ_1AS.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-Eduardo21620095/files/7378426/MAPA_MENTAL_CONJUNTOSYRELACIONES_EDUARDO_TOMAS_FERIA_ORTIZ_1AS.pdf)

**Comment by lucero012** [comment]
De acuerdo a la rubrica, cumple con los temas citados. y es entendible su información. 
de calificación le doy un (17%)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
